env:
    DEPLOY_RELEASE: 0.21.1
    GH_TOKEN: ENCRYPTED[7a45c1bfc23b47bdf2bf67d0e5936e16314c88d0ecc3932c44e7c14df46b763362815f2522305c5c42ce09f35a219b1c]

macos_task:
    # Basic metadata:
    name: dmg-bundle

    # The build machine:
    macos_instance:
      image: ghcr.io/cirruslabs/macos-monterey-base:latest

    # Instructions:
    bundle_script: |
      curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      bash Mambaforge-$(uname)-$(uname -m).sh -b -p "${HOME}/conda"
      source "${HOME}/conda/etc/profile.d/conda.sh"
      conda activate
      cd conda/osx
      bash ./create_bundle.sh
      mamba install gh
      gh repo set-default $CIRRUS_REPO_FULL_NAME
      gh release upload "$DEPLOY_RELEASE" FreeCAD*

    # dmg_artifacts:
    #   path: conda/osx/FreeCAD*

linux_task:
    # Basic metadata:
    name: appimage-bundle

    # The build machine:
    compute_engine_instance:
      image_project: cirrus-images
      image: family/docker-builder-arm64
      platform: linux
      architecture: arm64

    # Environment variables:
    env:
      DEBIAN_FRONTEND: noninteractive

    # Instructions:
    bundle_script: |
      apt update
      apt install curl fuse -y
      apt-get download libc6;
      dpkg -x libc6*.deb libc6;
      curl -LO https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage;
      curl -LO https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage;
      chmod a+x appimagetool-$(uname -m).AppImage;
      curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      export HOME='/home/cirrus-ci-build'
      bash Mambaforge-$(uname)-$(uname -m).sh -b -p "${HOME}/mambaforge"
      source "${HOME}/mambaforge/etc/profile.d/conda.sh"
      conda activate
      cd conda/linux
      bash ./create_bundle.sh
      mamba install gh
      gh repo set-default $CIRRUS_REPO_FULL_NAME
      gh release upload "$DEPLOY_RELEASE" FreeCAD*

    # appimage_artifacts:
    #   path: conda/linux/FreeCAD*
