# This is a basic workflow to help you get started with Actions

name: source_creation

# Controls when the workflow will run
on:
#  schedule:
#   - cron: "0 20 * * 1"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["2024.2.1"]
        branch: ["2024.2.1"]

    steps:
      - name: Run a multi-line script
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY_OWNER}/FreeCAD
          touch freecad_version.txt
          wget https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF##*/}/make_version_file.py
          wget https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF##*/}/disable_git_info.patch
          cd FreeCAD
          git checkout ${{ matrix.branch }}
          git submodule update --init
          python ../make_version_file.py ../freecad_version.txt
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git apply ../disable_git_info.patch
          git commit -a -m "Disable git info write to Version.h"
          git archive HEAD -o ../freecad_source.tar
          git submodule foreach --recursive \
            "git archive HEAD --prefix=\$path/ -o \$sha1.tar && \
             tar -A -f \$toplevel/../freecad_source.tar \$sha1.tar && \
             rm \$sha1.tar"
          gzip ../freecad_source.tar
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: Ondsel-Development/FreeCAD
          repo_token: ${{ secrets.GH_TOKEN }}
          file: freecad*
          tag: ${{ matrix.tag }}
          overwrite: true
          file_glob: true
